name: ci
on: push

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - run: npm run build
      - name: verify docs are up-to-date
        run: |
          diff <(npx tsx utils/generate-docs.mts README.md) README.md || { cat <<EOF
          The documentation is not up-to-date. Run the following command to update:
          printf "%s\n" "\$(npx tsx utils/generate-docs.mts README.md)" > README.md
          EOF
          exit 1
          }
      - name: conditional release
        if: ${{ github.ref == 'refs/heads/dev' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release@25.0.2
